data-id_pago="{{$registros->id_pago}}"
data-fecha="{{$registros->fecha}}"
data-cuota="{{$registros->cuota}}"
data-detalles="{{$registros->detalles}}"
data-id_expediente="{{$expediente->id_expediente}}"